raml生成网页版API文档
	配置Sublime Text支持raml的package包
	preferences->package controll->install package->RAML Syntax Highlighter
	检查：view->语法->raml

.raml文件生成.html文件
	安装nodejs；
	用nodejs自带的npm输入命令：npm i -g raml2html
	查看raml2html命令：raml2html --help
	win下生成.html文件：
		raml2html C:\Users\sam\AppData\Roaming\npm\node_modules\raml2html\examples\example.raml > C:\Users\sam\AppData\Roaming\npm\node_modules\raml2html\examples\example.html//example可换成自定义名字